### ISSUE TITLE
Error [ERR_SOCKET_CLOSED]

### ISSUE THREAD

**Issue by alenpaul2001** [maple3142/cf-warp#14]
### General information

-   Ubuntu + 20.04LTS:
    -   How did you install it?
      `  sudo npm i -g cf-warp`
    - result:
   ```
 /usr/local/bin/cf-warp -> /usr/local/lib/node_modules/cf-warp/cli.js
+ cf-warp@1.2.4
added 7 packages from 4 contributors in 1.366s
```
---

### Exact steps to reproduce the problem

1. `sudo npm i -g cf-warp`

2. Open the CLI tool

### What should happen?
Everthing Should Have Worked 
### What happened instead?

```
(node:25529) UnhandledPromiseRejectionWarning: Error [ERR_SOCKET_CLOSED]: Socket is closed
    at TLSSocket.Socket._writeGeneric (net.js:704:18)
    at TLSSocket.connect (net.js:696:12)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:10)
(node:25529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by maple3142** [comment]
I think it is your network problem

**Comment by eayin2** [comment]
I had the same error using the npm package, but with the binaries it works. My guess was that a dependency might be missing?

**Comment by maple3142** [comment]
You could try testing it on multiple node.js version.
